# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'cppod' do
 pod 'MJExtension', '3.0.15.1'
 pod 'AFNetworking', '3.2.1'
 pod 'MBProgressHUD', '1.1.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cppod

end
